site_name: All MarkDown Notes

nav:
  - Index: 'MarkDown_Notes/index.md'
  - Bullet:
    - Contents: 'MarkDown_Notes/0.Bullet/index.md'
    - Agenda: 'MarkDown_Notes//0.Bullet/0.Agenda/index.md'
    - To-Do-list: 'MarkDown_Notes//0.Bullet/1.To-Do-list/index.md'
    - Growth: 'MarkDown_Notes//0.Bullet/2.Growth/index.md'
    - Interest: 'MarkDown_Notes//0.Bullet/3.Interest/index.md'
    - Password-Book: 'MarkDown_Notes//0.Bullet/4.Password-Book/index.md'
    - unsorted: 'MarkDown_Notes//0.Bullet/x.unsorted/index.md'
  - Mission:
    - Contents: 'MarkDown_Notes/1.Mission/index.md'
    - Log: 'MarkDown_Notes//1.Mission/a.Log/index.md'
    - Projec: 'MarkDown_Notes//1.Mission/b.Projec/index.md'
    - 学习: 'MarkDown_Notes//1.Mission/c.学习/index.md'
    - old: 'MarkDown_Notes//1.Mission/x.old/index.md'
  - Research:
    - Contents: 'MarkDown_Notes/2.Research/index.md'
    - Seminar: 'MarkDown_Notes//2.Research/1.Seminar/index.md'
    - Literature: 'MarkDown_Notes//2.Research/2.Literature/index.md'
    - idea: 'MarkDown_Notes//2.Research/3.idea/index.md'
    - Methodology: 'MarkDown_Notes//2.Research/4.Methodology/index.md'
  - Efficiency:
    - Contents: 'MarkDown_Notes/3.Efficiency/index.md'
    - file management: 'MarkDown_Notes//3.Efficiency/0.file management/index.md'
    - Software management: 'MarkDown_Notes//3.Efficiency/1.Software management/index.md'
  - Sundries:
    - Contents: 'MarkDown_Notes/4.Sundries/index.md'
    - first year: 'MarkDown_Notes//4.Sundries/first year/index.md'
    - other people: 'MarkDown_Notes//4.Sundries/other people/index.md'


repo_url: https://github.com/ping-armo-fati/My-All-MD-sphinx-rtd-mirror

theme:
  name: mkdocs
  highlightjs: true
  user_color_mode_toggle: true
  feature:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
  hljs_languages:
    - yaml
    - rust
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  navigation_depth: 2
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon:
        name:
