site_name: MarkDown Notes

nav:
  - Home: 'Home.md'
  - Index: 'index.md'
  - Bullet:
    - Contents: '0.Bullet/index.md'
    - Habits: '0.Bullet/0.Habits/index.md'
    - Work-out: '0.Bullet/1.Work-out/index.md'
    - memoirs: '0.Bullet/2.memoirs/index.md'
    - Interest: '0.Bullet/3.Interest/index.md'
    - Password-Book: '0.Bullet/4.Password-Book/index.md'
    - Reading: '0.Bullet/5.Reading/index.md'
    - To-Do-list: '0.Bullet/6.To-Do-list/index.md'
    - unsorted: '0.Bullet/x.unsorted/index.md'
  - Project:
    - Contents: '1.Project/index.md'
    - Log: '1.Project/0.Log/index.md'
    - ROS: '1.Project/1.ROS/index.md'
    - Mujoco: '1.Project/2.Mujoco/index.md'
    - CGAL: '1.Project/3.CGAL/index.md'
    - GYM: '1.Project/4.GYM/index.md'
    - old: '1.Project/5.old/index.md'
  - Learn:
    - Contents: '2.Learn/index.md'
    - overview: '2.Learn/0.overview/index.md'
    - math: '2.Learn/1.math/index.md'
    - Roboticd: '2.Learn/2.Roboticd/index.md'
    - base-coding: '2.Learn/3.base-coding/index.md'
    - python: '2.Learn/4.python/index.md'
    - C++: '2.Learn/5.C++/index.md'
  - Research:
    - Contents: '3.Research/index.md'
    - Seminar: '3.Research/1.Seminar/index.md'
    - Literature: '3.Research/2.Literature/index.md'
    - idea: '3.Research/3.idea/index.md'
  - Research-Method:
    - Contents: '4.Research-Method/index.md'
    - discipline: '4.Research-Method/discipline/index.md'
    - experience: '4.Research-Method/experience/index.md'
    - Experiment: '4.Research-Method/Experiment/index.md'
    - paper submit: '4.Research-Method/paper submit/index.md'
  - Efficiency:
    - Contents: '5.Efficiency/index.md'
    - file management: '5.Efficiency/0.file management/index.md'
    - Software management: '5.Efficiency/1.Software management/index.md'
  - Sundries:
    - Contents: '6.Sundries/index.md'
    - first year: '6.Sundries/first year/index.md'
    - other people: '6.Sundries/other people/index.md'



repo_url: https://github.com/ping-armo-fati/My-All-MD-sphinx-rtd-mirror

theme:
  name: mkdocs
  highlightjs: true
  user_color_mode_toggle: true
  sticky_navigation: true
  feature:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
  hljs_languages:
    - yaml
    - rust
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  navigation_depth: 2
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon:
        name:
