site_name: All MarkDown Notes
nav:
  - Home: index.md
  - About: contents.md

repo_url: https://github.com/ping-armo-fati/My-All-MD-sphinx-rtd-mirror

theme:
  name: mkdocs
  highlightjs: true
  user_color_mode_toggle: true
  feature:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
  hljs_languages:
    - yaml
    - rust
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  navigation_depth: 2
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon:
        name:

